import crv1 from "../assets/images/cars/CR-V.png";
import crv2 from "../assets/images/cars/CR-V2.png";
import allNewRush from "../assets/images/cars/AllNewRush.png";

export const dummyRecommendationCars = [
  {
    id: 1,
    name: "All New Rush",
    img: allNewRush,
    type: "SUV",
    capacity: "6 People",
    price: 72,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 2,
    name: "CR-V",
    img: crv1,
    type: "SUV",
    capacity: "6 People",
    price: 80,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 3,
    name: "All New Terios",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 74,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 4,
    name: "CR-V",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 80,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 5,
    name: "MGZX Exclusive",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 76,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 6,
    name: "New MGZS",
    img: allNewRush,
    type: "SUV",
    capacity: "6 People",
    price: 80,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 7,
    name: "MGZX Excite",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 74,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 8,
    name: "New MGZS",
    img: allNewRush,
    type: "SUV",
    capacity: "6 People",
    price: 80,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 9,
    name: "All New Rush 2",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 73,
    gasoline: "75L",
    gear: "Automatic",
  },
  {
    id: 10,
    name: "CR-V 2",
    img: allNewRush,
    type: "SUV",
    capacity: "6 People",
    price: 81,
    gasoline: "85L",
    gear: "Manual",
  },
  {
    id: 11,
    name: "All New Terios 2",
    img: allNewRush,
    type: "SUV",
    capacity: "6 People",
    price: 75,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 12,
    name: "MGZX Exclusive 2",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 77,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 13,
    name: "New MGZS 2",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 81,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 14,
    name: "MGZX Excite 2",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 75,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 15,
    name: "New MGZS 3",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 81,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 16,
    name: "All New Rush 3",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 74,
    gasoline: "75L",
    gear: "Automatic",
  },
  {
    id: 17,
    name: "CR-V 3",
    img: crv1,
    type: "SUV",
    capacity: "6 People",
    price: 82,
    gasoline: "85L",
    gear: "Manual",
  },
  {
    id: 18,
    name: "All New Terios 3",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 76,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 19,
    name: "MGZX Exclusive 3",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 78,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 20,
    name: "New MGZS 4",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 82,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 21,
    name: "MGZX Excite 3",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 76,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 22,
    name: "New MGZS 5",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 82,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 23,
    name: "All New Rush 4",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 75,
    gasoline: "75L",
    gear: "Automatic",
  },
  {
    id: 24,
    name: "CR-V 4",
    img: crv1,
    type: "SUV",
    capacity: "6 People",
    price: 83,
    gasoline: "85L",
    gear: "Manual",
  },
  {
    id: 25,
    name: "All New Terios 4",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 77,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 26,
    name: "MGZX Exclusive 4",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 79,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 27,
    name: "New MGZS 6",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 83,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 28,
    name: "MGZX Excite 4",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 77,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 29,
    name: "New MGZS 7",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 83,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 30,
    name: "All New Rush 5",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 76,
    gasoline: "75L",
    gear: "Automatic",
  },
  {
    id: 31,
    name: "CR-V 5",
    img: crv1,
    type: "SUV",
    capacity: "6 People",
    price: 84,
    gasoline: "85L",
    gear: "Manual",
  },
  {
    id: 32,
    name: "All New Terios 5",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 78,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 33,
    name: "MGZX Exclusive 5",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 80,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 34,
    name: "New MGZS 8",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 84,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 35,
    name: "MGZX Excite 5",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 78,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 36,
    name: "New MGZS 9",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 84,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 37,
    name: "All New Rush 6",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 77,
    gasoline: "75L",
    gear: "Automatic",
  },
  {
    id: 38,
    name: "CR-V 6",
    img: crv1,
    type: "SUV",
    capacity: "6 People",
    price: 85,
    gasoline: "85L",
    gear: "Manual",
  },
  {
    id: 39,
    name: "All New Terios 6",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 79,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 40,
    name: "MGZX Exclusive 6",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 81,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 41,
    name: "New MGZS 10",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 85,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 42,
    name: "MGZX Excite 6",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 79,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 43,
    name: "New MGZS 11",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 85,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 44,
    name: "All New Rush 7",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 78,
    gasoline: "75L",
    gear: "Automatic",
  },
  {
    id: 45,
    name: "CR-V 7",
    img: crv1,
    type: "SUV",
    capacity: "6 People",
    price: 86,
    gasoline: "85L",
    gear: "Manual",
  },
  {
    id: 46,
    name: "All New Terios 7",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 80,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 47,
    name: "MGZX Exclusive 7",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 82,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 48,
    name: "New MGZS 12",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 86,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 49,
    name: "MGZX Excite 7",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 80,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 50,
    name: "New MGZS 13",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 86,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 51,
    name: "All New Rush 8",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 79,
    gasoline: "75L",
    gear: "Automatic",
  },
  {
    id: 52,
    name: "CR-V 8",
    img: crv1,
    type: "SUV",
    capacity: "6 People",
    price: 87,
    gasoline: "85L",
    gear: "Manual",
  },
  {
    id: 53,
    name: "All New Terios 8",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 81,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 54,
    name: "MGZX Exclusive 8",
    img: crv1,
    type: "Hatchback",
    capacity: "4 People",
    price: 83,
    gasoline: "70L",
    gear: "Manual",
  },
  {
    id: 55,
    name: "New MGZS 14",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 87,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 56,
    name: "MGZX Excite 8",
    img: crv2,
    type: "Hatchback",
    capacity: "4 People",
    price: 81,
    gasoline: "90L",
    gear: "Manual",
  },
  {
    id: 57,
    name: "New MGZS 15",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 87,
    gasoline: "80L",
    gear: "Manual",
  },
  {
    id: 58,
    name: "All New Rush 9",
    img: crv2,
    type: "SUV",
    capacity: "6 People",
    price: 80,
    gasoline: "75L",
    gear: "Automatic",
  },
];
